CREATE TABLE IF NOT EXISTS `detailsligneproduit` (
  `RefLycee` char(30) NOT NULL,
  `Id` int(3) NOT NULL,
  `DateChangement` date DEFAULT NULL,
  `IdTVA` int(10) DEFAULT NULL,
  `Gratuit` tinyint(1) DEFAULT NULL,
  `PUHT` decimal(12,4) DEFAULT NULL,
  `SortieEntree` char(1) DEFAULT NULL,
  `IdUsers` int(10) DEFAULT NULL,
  `PUTTC` decimal(12,4) DEFAULT NULL,
  `Utilisation` int(10) DEFAULT NULL,
  `OC` varchar(20) DEFAULT NULL,
  `Quantite` int(3) DEFAULT NULL,
  PRIMARY KEY (`RefLycee`,`Id`),
  FOREIGN KEY (`RefLycee`) REFERENCES produit(`RefLycee`),
  FOREIGN KEY (`IdTVA`) REFERENCES tva(`Id`),
  FOREIGN KEY (`IdUsers`) REFERENCES users(`Id`),
  FOREIGN KEY (`OC`) REFERENCES objetconfectionne(`ref`),
  FOREIGN KEY (`Utilisation`) REFERENCES utilisation(`Id`)
);