CREATE TABLE IF NOT EXISTS `objetconfectionne` (
  `Ref` varchar(20) NOT NULL,
  `Id` int(3) NOT NULL,
  `Annee` int(4) NOT NULL,
  `Designation` char(100) NOT NULL,
  `NbPrevision` int(2) NOT NULL,
  `Professeur` int(2) NOT NULL,
  `Destination` char(30) NOT NULL,
  `DateEmi` date NOT NULL,
  `DateFabri` date NOT NULL,
  `CoefCorrection` decimal(10,2) NOT NULL,
  `NbRealise` int(2) NOT NULL,
  `Temps` decimal(10,2) NOT NULL,
  `TotalMatiere` decimal(12,4) NOT NULL,
  `TotalFrais` decimal(12,4) NOT NULL,
  `TotalCoutEleve` decimal(12,4) NOT NULL,
  `CoutMachine` decimal(12,4) NOT NULL,
  `TotalCoutPublic` decimal(12,4) NOT NULL,
  `PrixUnitairePublic` decimal(12,4) NOT NULL,
  `PrixEleveUnitaire` decimal(12,4) NOT NULL,
  `CoutMachinePU` decimal(10,2) NOT NULL,
  `Quantite` int(3) NOT NULL,
  `StockInital` int(3) NOT NULL,
  PRIMARY KEY (`Ref`), 
  FOREIGN KEY (`Professeur`) REFERENCES users(`Id`)
);