CREATE TABLE IF NOT EXISTS `produit` (
`RefLycee` varchar(30) NOT NULL,
  `Id` int(3) NOT NULL,
  `RefFournisseur` varchar(30) NOT NULL,
  `Designation` varchar(100) NOT NULL,
  `IdUniteAchat` int(3) NOT NULL,
  `IdFournisseur` int(3) NOT NULL,
  `QuantiteTotal` decimal(12,4) NOT NULL,
  `Obselete` tinyint(1) NOT NULL,
  `StockAlerte` int(2) NOT NULL,
  `PUTTCPondere` decimal(12,4) NOT NULL,
  `Coloris` char(15) NOT NULL,
  `IdSection` int(3) NOT NULL,
  `StockInitial` decimal(12,4) NOT NULL,
  `PondereInitial` decimal(12,4) NOT NULL,
  PRIMARY KEY (`RefLycee`),
  FOREIGN KEY (`IdFournisseur`) REFERENCES fournisseurs(`Id`),
  FOREIGN KEY (`IdSection`) REFERENCES section(`Id`),
  FOREIGN KEY (`IdUniteAchat`) REFERENCES unite(`Id`)
)ENGINE=InnoDB;
